worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    upstream api {
        server api:8000;
    }

    upstream dashboard {
        server dashboard:8501;
    }

    upstream grafana {
        server grafana:3000;
    }

    server {
        listen 80;

        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /dashboard/ {
            rewrite ^/dashboard/(.*) /$1 break;
            proxy_pass http://dashboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /grafana/ {
            rewrite ^/grafana/(.*) /$1 break;
            proxy_pass http://grafana;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
